config/routes.rb
Rails.application.routes.draw do

  resources :authors
  resources :books, only: [:index, :show]
  # resources :authorships, only: [:create]
  get "/", to: "welcome#index"
  delete "/danger/clear/all", to: "welcome#clairol"

  resources :books do
    resources :authorships, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :authorships, dependent: :destroy
  has_many :books, through: :authorships

  validates :name, presence: true, uniqueness: true
  
  validates :birth_year, presence: true, numericality: {
    greater_than: 0,
    only_integer: true,
    less_than_or_equal_to: DateTime.now.year,

  }

end

app/models/authorship.rb
class Authorship < ApplicationRecord
  belongs_to :book
  belongs_to :author

  validates_uniqueness_of :book, scope: :author
  
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :authorships, dependent: :destroy
  has_many :authors, through: :authorships
end

app/models/domain_mapping.rb
class DomainMapping < ApplicationRecord

  def self.find_by_host(host)
    subdomainest = host.split(".").first
    self.find_by(subdomain: subdomainest)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :fetch_domain_mapping


  def fetch_domain_mapping
    @mapping = DomainMapping.find_by_host(request.host)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_action :gat_author, only: [:show, :edit, :update]

  def index
    @authors = Author.all
  end

  def show
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to @author
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @author.update(author_params)
      redirect_to @author
    else
      render :edit
    end
  end

  def destroy
    Author.destroy(params[:id])
    redirect_to authors_path
  end

  private
  def gat_author
    @author = Author.find(params[:id])
  end

  def author_params 
    params.require(:author).permit(:name, :birth_year)
  end

end

app/controllers/authorships_controller.rb
class AuthorshipsController < ApplicationController

  def create
    @authorship = Authorship.create(author_id: params[:authorship][:author_id], book_id: params[:book_id])
    redirect_to @authorship.book
  end

  def destroy
    Authorship.destroy(params[:id])
    redirect_to book_path(params[:book_id])
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @all_authors = Author.all
    @book = Book.includes(:authors).find(params[:id])
    @authorship = Authorship.new
    @authorship.book = @book
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_before_action :verify_authenticity_token, only: [:clairol]

  def index
    file = File.open("db/seeds_authors_books.rb", "rb")
    @seed_file = file.read
    file.close
  end

  def clairol
    require_relative "../../db/seeds_authors_books.rb" #ugh?
    render json: { ok: true }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_form.erb
<% if @author.errors && @author.errors.any? %>
<ul>
  <% @author.errors.full_messages.each do |message| %>
  <li>
    <%= message %>
  </li>
  <% end %>
</ul>
<% end %>


<%= form_for @author do |form| %>

  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :birth_year %>
    <%= form.text_field :birth_year %>
  </p>

  <%= form.submit %>

<% end %>

app/views/authors/edit.erb
<h1>Edit <%= @author.name %></h1>
<%= render "form" %>

app/views/authors/index.erb
<h1>Authors!</h1>
<%= link_to "New Author", new_author_path %>
<ul>
<% @authors.each do |author| %>
  <li>
    <%= link_to author.name, author %> (b. <%= author.birth_year %>)
  </li>
<% end %>
</ul>

app/views/authors/new.erb
<h1>New Author</h1>
<%= render "form" %>

app/views/authors/show.erb
<h1><%= @author.name %> (b. <%= @author.birth_year %>)</h1>
Books:
<% unless @author.books.any? %>
  <em>(none)</em>
<% else %>
  <ul>
    <% @author.books.each do |book| %> 
    <li><%= link_to book.title, book %></li>
    <% end %>
  </ul>
<% end %>
<nav>
<%= link_to "Edit #{ @author.name }", edit_author_path(@author) %>
<%= form_with model: @author, method: :delete, local: true do |form| %>
  <%= form.submit "Delete #{ @author.name }" %>
<% end %>
</nav>

app/views/authorships/_form.erb
<%= form_with model: @authorship, url: book_authorships_path(@authorship.book.id), local: true do |form| %>
    <%= form.label :author_id %>
    <%= form.collection_select :author_id, @all_authors, :id, :name %>
    <%= form.submit "Add author" %>
<% end %>

app/views/authorships/new.erb
<%= render "form" %>

app/views/books/index.erb
<h1>Books!</h1>

<ul>
<% @books.each do |book| %>
  <li>
    <%= link_to book.title, book %> (<%= book.pages %> pages)
  </li>
<% end %>
</ul>

app/views/books/show.erb
<h1><%= @book.title %> (<%= @book.pages %> pages)</h1>
<h2>Authors:</h2>
<ul>
  <% @book.authorships.each do |authorship| %>
    <li>
      <%= link_to "#{ authorship.author.name } (b. #{ authorship.author.birth_year })", author_path(authorship.author) %>
      <%= form_for [@book, authorship], method: :delete, local: true do |form| %>
        <%= form.submit "Remove author" %>
      <% end%>
    </li>
  <% end%>
</ul>

<%= render "authorships/form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= render :partial => "welcome/app_name" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <ol>
        <li>
          <%= link_to "Authors Index", authors_path %>
        </li>
        <li>
          <%= link_to "Books Index", books_path %>
        </li>
      </ol>
      <hr />
    </nav>
    <%= yield %>
  </body>
</html>

app/views/welcome/_app_name.erb
<%= @mapping ? @mapping.cohort_name.possessive : "" %> Rails practice

app/views/welcome/index.erb
<h1>Welcome to <%= render :partial => "welcome/app_name" %>!</h1>

<p>Your mission is to recreate this app (you can skip this page) to the best of your ability. Work with your group members to find all the features of this site, and implement them &mdash; starting with <code>rails new</code> and using the know-how that you've built through the labs. Failing that, error messages, Google, your neighbors, and your instructors can help!</p>

<p>Work through the <strong>entire</strong> Authors controller (finish it!) before you start work on the Books controller. If you want to do your migrations / associations for all your models first, that's fine.</p>

<h2>Some things to think about (in rough order of when you should probably think about them):</h2>
<ol>
  <li>Models and relationships
    <ol>
      <li>How many books can an author have?</li>
      <li>How many authors can a book have?</li>
    </ol>
    (Following the links in the header should help you answer these questions! Make your decisions based on the <em>functionality of the app</em>.)
  </li>
  <li>
    <code>rails g model</code>
  </li>
  <li>Migrations</li>
  <li>Associations</li>
  <li>Routes</li>
  <li>
    <code>rails g controller</code>
  </li>
  <li>Views (if you haven't run <code>rails s</code> yet you should now)</li>
  <li>Strong Params</li>
  <li>Validations</li>
  <li><code>form.collection_select</code></li>
  <li>Nested Routes (this app uses them...somewhere. 🙃 You don't have to, but feel free to challenge yourself!)</li>
  <li>MVC (refactoring...?)</li>
  <li><code>before_action</code> (more refactoring...?!?)</li>
</ol>

<h2>Seed data (if you want it):</h2>
<textarea style="width: 90%; font-family: monospace; min-height: 400px;">
<%= @seed_file %>
</textarea>